title: Thinking outside of the box
description: A guide and demonstration of the powerful new properties of the CSS flexbox
theme: jekyll-theme-cayman

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: /:name/
